default: &default
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: develop
  database: gist_github_development
test:
  <<: *default
  username: develop
  database: gist_github_test

staging:
  <<: *default
  username: develop
  database: gist_github_staging

production:
  <<: *default
  username: develop
  database: gist_github_production
